// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD1kDsfxKmTSseVMZgID6wgPM4Tqg3wWw',
    appId: '1:762667772377:web:e2046c4417b193538bd1c8',
    messagingSenderId: '762667772377',
    projectId: 'recycle-6f23d',
    authDomain: 'recycle-6f23d.firebaseapp.com',
    storageBucket: 'recycle-6f23d.appspot.com',
    measurementId: 'G-6BPJPY4PG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_JV6wVoHpjiNeX4pkaLyp4m1YpJBhjc8',
    appId: '1:762667772377:android:5c3c171535b865c98bd1c8',
    messagingSenderId: '762667772377',
    projectId: 'recycle-6f23d',
    storageBucket: 'recycle-6f23d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ60qGQwe8ztRRL4jdB9OwPb_bN5ONUlQ',
    appId: '1:762667772377:ios:8296c3099c2c47d48bd1c8',
    messagingSenderId: '762667772377',
    projectId: 'recycle-6f23d',
    storageBucket: 'recycle-6f23d.appspot.com',
    iosBundleId: 'com.example.recycleit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ60qGQwe8ztRRL4jdB9OwPb_bN5ONUlQ',
    appId: '1:762667772377:ios:8296c3099c2c47d48bd1c8',
    messagingSenderId: '762667772377',
    projectId: 'recycle-6f23d',
    storageBucket: 'recycle-6f23d.appspot.com',
    iosBundleId: 'com.example.recycleit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD1kDsfxKmTSseVMZgID6wgPM4Tqg3wWw',
    appId: '1:762667772377:web:eb7997c815153c518bd1c8',
    messagingSenderId: '762667772377',
    projectId: 'recycle-6f23d',
    authDomain: 'recycle-6f23d.firebaseapp.com',
    storageBucket: 'recycle-6f23d.appspot.com',
    measurementId: 'G-Z7SG5Y5Y74',
  );
}
